/* autogenerated by Processing revision 1286 on 2022-11-24 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class discoballthingy extends PApplet {

float x,y,z;
float angle= PI/200;

 public void setup() {
  /* size commented out by preprocessor */;
  x = width/2;
  y = height/2;
  z = 0;
  noStroke();
  colorMode(HSB, 360, 100, 100);
  frameRate(12);
}

 public void draw() 
{ 
background(1);
lights();
rotateY(angle);
float cameraY = height/1.0f;
  float fov = mouseX/PApplet.parseFloat(width) * PI/3;
  float cameraZ = cameraY / tan(fov / 2.0f);
  float aspect = PApplet.parseFloat(width)/PApplet.parseFloat(height);
 
  perspective(fov, aspect, cameraZ/8.0f, cameraZ*3.0f);
  
  translate(width/2+30, height/2, 0);
  rotateX(-PI/6);
  rotateY(PI/3 + mouseY/PApplet.parseFloat(height) * PI);
         

pushMatrix();
translate(400, height*0.35f, 200);
stroke(1);
sphere(360);
popMatrix();
 
 
float hue = random(0, 360);
fill(hue, hue, hue);
}


  public void settings() { size(1200, 1200, P3D); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "--full-screen", "--bgcolor=#666666", "--stop-color=#cccccc", "discoballthingy" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
